// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: apps/router/pb/rpc.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SEARCH_TYPE int32

const (
	SEARCH_TYPE_SEARCH_TYPE_UNSPECIFIED  SEARCH_TYPE = 0
	SEARCH_TYPE_SEARCH_TYPE_ROUTER_ID    SEARCH_TYPE = 1
	SEARCH_TYPE_SEARCH_TYPE_CLUSTER_NAME SEARCH_TYPE = 2
	SEARCH_TYPE_SEARCH_TYPE_PROJECT_CODE SEARCH_TYPE = 3
	SEARCH_TYPE_SEARCH_TYPE_PROJECT_LINE SEARCH_TYPE = 4
	SEARCH_TYPE_SEARCH_TYPE_PROJECT_DESC SEARCH_TYPE = 5
)

// Enum value maps for SEARCH_TYPE.
var (
	SEARCH_TYPE_name = map[int32]string{
		0: "SEARCH_TYPE_UNSPECIFIED",
		1: "SEARCH_TYPE_ROUTER_ID",
		2: "SEARCH_TYPE_CLUSTER_NAME",
		3: "SEARCH_TYPE_PROJECT_CODE",
		4: "SEARCH_TYPE_PROJECT_LINE",
		5: "SEARCH_TYPE_PROJECT_DESC",
	}
	SEARCH_TYPE_value = map[string]int32{
		"SEARCH_TYPE_UNSPECIFIED":  0,
		"SEARCH_TYPE_ROUTER_ID":    1,
		"SEARCH_TYPE_CLUSTER_NAME": 2,
		"SEARCH_TYPE_PROJECT_CODE": 3,
		"SEARCH_TYPE_PROJECT_LINE": 4,
		"SEARCH_TYPE_PROJECT_DESC": 5,
	}
)

func (x SEARCH_TYPE) Enum() *SEARCH_TYPE {
	p := new(SEARCH_TYPE)
	*p = x
	return p
}

func (x SEARCH_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SEARCH_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_router_pb_rpc_proto_enumTypes[0].Descriptor()
}

func (SEARCH_TYPE) Type() protoreflect.EnumType {
	return &file_apps_router_pb_rpc_proto_enumTypes[0]
}

func (x SEARCH_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SEARCH_TYPE.Descriptor instead.
func (SEARCH_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_apps_router_pb_rpc_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_router_pb_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_apps_router_pb_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_apps_router_pb_rpc_proto_rawDescGZIP(), []int{0}
}

type DescRouteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: validate:"required"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"required"`
}

func (x *DescRouteReq) Reset() {
	*x = DescRouteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_router_pb_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescRouteReq) ProtoMessage() {}

func (x *DescRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_router_pb_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescRouteReq.ProtoReflect.Descriptor instead.
func (*DescRouteReq) Descriptor() ([]byte, []int) {
	return file_apps_router_pb_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *DescRouteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRouteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: validate:"required"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"required"`
}

func (x *DeleteRouteReq) Reset() {
	*x = DeleteRouteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_router_pb_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteReq) ProtoMessage() {}

func (x *DeleteRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_router_pb_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteReq.ProtoReflect.Descriptor instead.
func (*DeleteRouteReq) Descriptor() ([]byte, []int) {
	return file_apps_router_pb_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRouteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryRouteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchType SEARCH_TYPE `protobuf:"varint,1,opt,name=search_type,json=searchType,proto3,enum=K8sGenie.router.SEARCH_TYPE" json:"search_type,omitempty"`
	KeyWord    string      `protobuf:"bytes,2,opt,name=key_word,json=keyWord,proto3" json:"key_word,omitempty"`
}

func (x *QueryRouteReq) Reset() {
	*x = QueryRouteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apps_router_pb_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRouteReq) ProtoMessage() {}

func (x *QueryRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_router_pb_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRouteReq.ProtoReflect.Descriptor instead.
func (*QueryRouteReq) Descriptor() ([]byte, []int) {
	return file_apps_router_pb_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRouteReq) GetSearchType() SEARCH_TYPE {
	if x != nil {
		return x.SearchType
	}
	return SEARCH_TYPE_SEARCH_TYPE_UNSPECIFIED
}

func (x *QueryRouteReq) GetKeyWord() string {
	if x != nil {
		return x.KeyWord
	}
	return ""
}

var File_apps_router_pb_rpc_proto protoreflect.FileDescriptor

var file_apps_router_pb_rpc_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x62,
	0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x4b, 0x38, 0x73, 0x47,
	0x65, 0x6e, 0x69, 0x65, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x1a, 0x1a, 0x61, 0x70, 0x70,
	0x73, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x1e, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x63, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x20, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x69, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x3d, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x4b, 0x38, 0x73, 0x47, 0x65,
	0x6e, 0x69, 0x65, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x45, 0x41, 0x52, 0x43,
	0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x57, 0x6f, 0x72, 0x64, 0x2a, 0xbd, 0x01,
	0x0a, 0x0b, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x1b, 0x0a,
	0x17, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x45,
	0x41, 0x52, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x52,
	0x5f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x4c, 0x55, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x4e, 0x41, 0x4d,
	0x45, 0x10, 0x02, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x10,
	0x03, 0x12, 0x1c, 0x0a, 0x18, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x04, 0x12,
	0x1c, 0x0a, 0x18, 0x53, 0x45, 0x41, 0x52, 0x43, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50,
	0x52, 0x4f, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x44, 0x45, 0x53, 0x43, 0x10, 0x05, 0x32, 0x96, 0x02,
	0x0a, 0x03, 0x52, 0x70, 0x63, 0x12, 0x3d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x4b, 0x38, 0x73, 0x47, 0x65, 0x6e, 0x69, 0x65, 0x2e,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x4b,
	0x38, 0x73, 0x47, 0x65, 0x6e, 0x69, 0x65, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x3d, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x4b, 0x38, 0x73, 0x47, 0x65, 0x6e, 0x69, 0x65, 0x2e, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x1a, 0x17, 0x2e, 0x4b, 0x38, 0x73,
	0x47, 0x65, 0x6e, 0x69, 0x65, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x12, 0x1f, 0x2e, 0x4b, 0x38, 0x73, 0x47, 0x65, 0x6e, 0x69, 0x65, 0x2e, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x4b, 0x38, 0x73, 0x47, 0x65, 0x6e, 0x69, 0x65, 0x2e, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x0a,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x1e, 0x2e, 0x4b, 0x38, 0x73,
	0x47, 0x65, 0x6e, 0x69, 0x65, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x4b, 0x38, 0x73,
	0x47, 0x65, 0x6e, 0x69, 0x65, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x53, 0x65, 0x74, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x65, 0x65, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x71, 0x69, 0x61, 0x6f, 0x67, 0x79, 0x39, 0x31, 0x2f, 0x4b, 0x38, 0x73,
	0x47, 0x65, 0x6e, 0x69, 0x65, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apps_router_pb_rpc_proto_rawDescOnce sync.Once
	file_apps_router_pb_rpc_proto_rawDescData = file_apps_router_pb_rpc_proto_rawDesc
)

func file_apps_router_pb_rpc_proto_rawDescGZIP() []byte {
	file_apps_router_pb_rpc_proto_rawDescOnce.Do(func() {
		file_apps_router_pb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_apps_router_pb_rpc_proto_rawDescData)
	})
	return file_apps_router_pb_rpc_proto_rawDescData
}

var file_apps_router_pb_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_router_pb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apps_router_pb_rpc_proto_goTypes = []any{
	(SEARCH_TYPE)(0),       // 0: K8sGenie.router.SEARCH_TYPE
	(*Empty)(nil),          // 1: K8sGenie.router.Empty
	(*DescRouteReq)(nil),   // 2: K8sGenie.router.DescRouteReq
	(*DeleteRouteReq)(nil), // 3: K8sGenie.router.DeleteRouteReq
	(*QueryRouteReq)(nil),  // 4: K8sGenie.router.QueryRouteReq
	(*Spec)(nil),           // 5: K8sGenie.router.Spec
	(*Router)(nil),         // 6: K8sGenie.router.Router
	(*RouterSet)(nil),      // 7: K8sGenie.router.RouterSet
}
var file_apps_router_pb_rpc_proto_depIdxs = []int32{
	0, // 0: K8sGenie.router.QueryRouteReq.search_type:type_name -> K8sGenie.router.SEARCH_TYPE
	1, // 1: K8sGenie.router.Rpc.CreateTable:input_type -> K8sGenie.router.Empty
	5, // 2: K8sGenie.router.Rpc.CreateRoute:input_type -> K8sGenie.router.Spec
	3, // 3: K8sGenie.router.Rpc.DeleteRoute:input_type -> K8sGenie.router.DeleteRouteReq
	4, // 4: K8sGenie.router.Rpc.QueryRoute:input_type -> K8sGenie.router.QueryRouteReq
	1, // 5: K8sGenie.router.Rpc.CreateTable:output_type -> K8sGenie.router.Empty
	6, // 6: K8sGenie.router.Rpc.CreateRoute:output_type -> K8sGenie.router.Router
	6, // 7: K8sGenie.router.Rpc.DeleteRoute:output_type -> K8sGenie.router.Router
	7, // 8: K8sGenie.router.Rpc.QueryRoute:output_type -> K8sGenie.router.RouterSet
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_router_pb_rpc_proto_init() }
func file_apps_router_pb_rpc_proto_init() {
	if File_apps_router_pb_rpc_proto != nil {
		return
	}
	file_apps_router_pb_model_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_apps_router_pb_rpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_router_pb_rpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DescRouteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_router_pb_rpc_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteRouteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apps_router_pb_rpc_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*QueryRouteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apps_router_pb_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_router_pb_rpc_proto_goTypes,
		DependencyIndexes: file_apps_router_pb_rpc_proto_depIdxs,
		EnumInfos:         file_apps_router_pb_rpc_proto_enumTypes,
		MessageInfos:      file_apps_router_pb_rpc_proto_msgTypes,
	}.Build()
	File_apps_router_pb_rpc_proto = out.File
	file_apps_router_pb_rpc_proto_rawDesc = nil
	file_apps_router_pb_rpc_proto_goTypes = nil
	file_apps_router_pb_rpc_proto_depIdxs = nil
}
